# Generated by Django 3.2.9 on 2021-11-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0002_auto_20211130_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='wid',
        ),
    ]
