# Generated by Django 3.2.9 on 2021-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0004_alter_order_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='lock_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
