# Generated by Django 3.2.9 on 2021-12-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0005_investment_lock_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reward',
            new_name='pool',
        ),
    ]
