# Generated by Django 3.2.9 on 2021-12-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0006_rename_reward_transaction_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.pair')),
            ],
        ),
    ]
