# Generated by Django 3.2.9 on 2021-12-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0008_remove_pool_campaign_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worth',
        ),
    ]
