# Generated by Django 3.2.9 on 2021-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0009_remove_order_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worth',
            field=models.FloatField(null=True),
        ),
    ]
