# Generated by Django 3.2.9 on 2021-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0010_order_worth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='worth',
            field=models.FloatField(default=0.0),
        ),
    ]
