# Generated by Django 3.2.9 on 2021-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0012_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(default='statistic', max_length=32),
        ),
    ]
