# Generated by Django 3.2.9 on 2022-01-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0014_auto_20220106_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentshift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentshift',
            name='run',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investmentshift',
            name='worth_at_end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investmentshift',
            name='worth_at_run',
            field=models.FloatField(),
        ),
    ]
