# Generated by Django 3.2.9 on 2022-01-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0015_auto_20220128_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pair',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
