# Generated by Django 3.2.9 on 2022-01-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0016_alter_price_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentshift',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentshift',
            name='stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentshift',
            name='worth_at_end',
            field=models.FloatField(null=True),
        ),
    ]
