# Generated by Django 3.2.9 on 2022-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0018_alter_price_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='pair_text',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
