# Generated by Django 3.2.9 on 2022-02-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0019_price_pair_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='shift',
        ),
    ]
