# Generated by Django 3.2.9 on 2022-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0020_remove_investment_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreward',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
