# Generated by Django 3.2.9 on 2022-02-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0021_alter_weeklyreward_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='maximum_spread',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='minimum_spread',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='safety_net',
        ),
        migrations.AddField(
            model_name='investment',
            name='auto_cancel_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='order_pair_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='investment',
            name='renew_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='investment',
            name='stop_bot_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='trigger_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='OrderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_spread', models.FloatField(default=0)),
                ('ask_spread', models.FloatField(default=0)),
                ('auto_cancel_bid_deviation', models.FloatField(default=0)),
                ('auto_cancel_ask_deviation', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.investment')),
            ],
        ),
        migrations.CreateModel(
            name='AutoCancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('way_down', models.BooleanField(default=True)),
                ('expire_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.investment')),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.pair')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.status')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='auto_cancel_order',
            field=models.ManyToManyField(related_name='auto_cancel_order', to='liquidminers.AutoCancelOrder'),
        ),
        migrations.AddField(
            model_name='investment',
            name='order_config',
            field=models.ManyToManyField(related_name='order_config', to='liquidminers.OrderConfig'),
        ),
    ]
