# Generated by Django 3.2.9 on 2022-02-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0022_auto_20220223_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='trigger_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
