# Generated by Django 3.2.9 on 2022-02-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0023_alter_investment_trigger_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfig',
            name='balance_allocation',
            field=models.FloatField(default=0),
        ),
    ]
