# Generated by Django 3.2.9 on 2022-02-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0025_remove_autocancelorder_way_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocancelorder',
            name='queue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='queue',
            field=models.IntegerField(default=1),
        ),
    ]
