# Generated by Django 3.2.9 on 2022-02-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0026_auto_20220224_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autocancelorder',
            old_name='price',
            new_name='ask_price',
        ),
        migrations.AddField(
            model_name='autocancelorder',
            name='bid_price',
            field=models.FloatField(default=0),
        ),
    ]
