# Generated by Django 3.2.9 on 2022-02-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0028_investment_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display', models.BooleanField(default=True, null=True)),
                ('kind', models.CharField(default='INFO', max_length=8, null=True)),
                ('subject', models.CharField(max_length=64, null=True)),
                ('content', models.TextField()),
                ('param', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('investment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.investment')),
            ],
        ),
        migrations.CreateModel(
            name='RewardCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('duration', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(null=True)),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.pool')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.week')),
            ],
        ),
        migrations.RemoveField(
            model_name='rewardsharing',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='rewardsharing',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='rewardsharing',
            name='week',
        ),
        migrations.AddField(
            model_name='rewardsharing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardsharing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreward',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreward',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreward',
            name='shared_total',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='rewardsharing',
            name='calculation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.rewardcalculation'),
        ),
    ]
