# Generated by Django 3.2.9 on 2022-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0029_auto_20220228_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardcalculation',
            old_name='timestamp',
            new_name='end',
        ),
        migrations.AddField(
            model_name='rewardcalculation',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
