# Generated by Django 3.2.9 on 2022-02-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0030_auto_20220228_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.pool'),
        ),
    ]
