# Generated by Django 3.2.9 on 2022-02-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0031_order_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.orderconfig'),
        ),
    ]
