# Generated by Django 3.2.9 on 2022-02-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0032_order_order_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_config',
            new_name='config',
        ),
    ]
