# Generated by Django 3.2.9 on 2022-02-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0033_rename_order_config_order_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='max_spread',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
