# Generated by Django 3.2.9 on 2022-03-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0035_alter_investment_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocancelorder',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.orderconfig'),
        ),
    ]
