# Generated by Django 3.2.9 on 2022-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0036_autocancelorder_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='renew_unfilled_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='buy_filled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='sell_filled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
