# Generated by Django 3.2.9 on 2022-03-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0037_auto_20220304_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsharing',
            name='week_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.weeklyreward'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.pool')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.status')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.week')),
            ],
        ),
    ]
