# Generated by Django 3.2.9 on 2022-03-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0038_auto_20220305_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardsharing',
            name='week_config',
        ),
        migrations.AddField(
            model_name='rewardsharing',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidminers.week'),
        ),
    ]
