# Generated by Django 3.2.9 on 2022-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0039_auto_20220305_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='method',
            field=models.CharField(default='GET', max_length=32, null=True),
        ),
    ]
