# Generated by Django 3.2.9 on 2022-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0040_apilog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='max_spread',
            field=models.FloatField(default=0.01, null=True),
        ),
    ]
