# Generated by Django 3.2.9 on 2022-03-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0041_alter_pool_max_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thread_id',
            field=models.CharField(default='DEFAULT', max_length=10),
        ),
    ]
