# Generated by Django 3.2.9 on 2022-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0042_order_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='param_update_check',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
