# Generated by Django 3.2.9 on 2022-04-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidminers', '0044_pool_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
