from liquidminers.views.admin_dashboard import admin_dashboard
from liquidminers.views.api_cancel_order import api_cancel_order
from liquidminers.views.bot import bot
from liquidminers.views.engine import engine
from liquidminers.views.exchange_monitor import cancel_admin_order
from liquidminers.views.exchange_monitor import create_admin_order
from liquidminers.views.exchange_monitor import exchange_monitor
from liquidminers.views.home import home
from liquidminers.views.initialization import initialization
from liquidminers.views.manager.home import stats
from liquidminers.views.markets import markets
from liquidminers.views.new_bot import new_bot
from liquidminers.views.other import under_construction
from liquidminers.views.register import register
from liquidminers.views.settings import settings
from liquidminers.views.test import test
from liquidminers.views.user_logout import user_logout
